# Generated by Django 5.0.1 on 2024-01-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="image_url",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
