# Generated by Django 5.0.1 on 2024-01-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_parser", "0002_newsitem_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="image_url",
            field=models.CharField(default="", max_length=200),
        ),
    ]
